### ISSUE TITLE
Test with latest ndarray

### ISSUE THREAD

**Issue by vbarrielle** [vbarrielle/sprs#102]
There's been a great refactor in ndarray (dimension type is now an array instead of a tuple). We need to check if we're compatible and if possible ensure that we build before and after the refactoring. It should work if using ndarray's type aliases.

**Comment by bluss** [comment]
Hi, I haven't made a new release yet. I was halfway hoping I would realize some kind of simplification of the dimension issue again. When moving from tuples to arrays, it fell out naturally to use a wrapper type I think. I've put a small discussion over in issue https://github.com/bluss/rust-ndarray/issues/238

**Comment by vbarrielle** [comment]
I wanted to try out before you released, to see if I had to change lots of things. I'm trying to build against ndarray master this evening, so I might have some feedback to put on issue bluss/rust-ndarray#238

**Comment by vbarrielle** [comment]
Latest sprs version (0.6) works against ndarray 0.10 and later.
