### ISSUE TITLE
Easy way to create an sparse matrix (maybe coo)?

### ISSUE THREAD

**Issue by z1mvader** [vbarrielle/sprs#108]
Hey! I was thinking that it would be pretty cool to add some simple way to create a csr or csc matrix providing everything using coo for example without having to specify the compressed row or column indices and using directly the row and column indices .

**Comment by vbarrielle** [comment]
Hello, you can use the [triplet matrix](https://docs.rs/sprs/0.5.0/sprs/struct.TripletMat.html) to more easily create sparse matrices. This format can then be converted to CSR/CSC.

**Comment by z1mvader** [comment]
Ohhhhh ok I should read more then :)

**Comment by vbarrielle** [comment]
My bad, the documentation is not really complete right now.
