### ISSUE TITLE
[QUESTION] Iterate over a row/column of a matrix

### ISSUE THREAD

**Issue by odarbelaeze** [vbarrielle/sprs#109]
Hey, it would be very convenient for me if I could iterate over a single row/column of the matrix, in a way similar to:

```
let matrix = CsMat::new(...);
for (i, j, value) in matrix.iter_over_row(row) {
   // do stuff
}
```

Is there any way to do this with the current implementation of matrix views? It could be there in the docs but I'm not familiar with the jargon, any help with this question would be greatly appreciated.

**Comment by vbarrielle** [comment]
Hello, if you want to iterate efficiently over a row of a matrix, first you must ensure that you have a matrix in the CSR format (the default). Then you can call `matrix.outer_view(row_index)` to get a view of the desired row, and then you can call `.iter()` on that view to get the elements of that row. In short:

```rust
let matrix = CsMat::new(...);
let row_index = 2;
for (j, value) in matrix.outer_view(row_index).iter() {
    // do stuff
}
```

If you want to iterate over a column, you must have a matrix in the CSC format (using `new_csc`), but then the code is essentially the same. In the jargon, the outer dimension is the dimension along which the storage is compressed, so rows for a CSR matrix, and columns for a CSC matrix. I probably should enhance the docs to make this point clear.

**Comment by odarbelaeze** [comment]
Thanks a lot @vbarrielle for the clear answer.
