### ISSUE TITLE
Serialization to the matrix market format

### ISSUE THREAD

**Issue by vbarrielle** [vbarrielle/sprs#115]
The [matrix market format](http://math.nist.gov/MatrixMarket/formats.html) is used for test matrices in the [suitesparse matrices collection](https://sparse.tamu.edu/about). Thus reading this format is a pre-requisite to more systematic testing.

**Comment by vbarrielle** [comment]
See #123 and #128 for progress. Still need to test on files taken from the collection but it looks like it should be possible now.

**Comment by rth** [comment]
This issue can be closed as fixed I think?

**Comment by vbarrielle** [comment]
You're right yes, there are a few issues like this one that are done but that I never thought to close.
