### ISSUE TITLE
Relax Copy bound to Clone

### ISSUE THREAD

**Issue by edibopp** [vbarrielle/sprs#121]
This issue was mentioned in #118. Thus I felt it would be good to make a separate issue for it, as I do not think it makes sense to handle it as part of that. Big integers or rationals would be an interesting use case, for example.

**Comment by mulimoen** [comment]
@vbarrielle While we are doing some breaking changes: Maybe we could change the constructor methods of `CsMatBase` so `new` does not do any sorting and we add a new method `new_sort` which acts as `new` does today?

**Comment by vbarrielle** [comment]
@mulimoen are you sure you wanted to comment on this issue? It looks like you wanted to comment on #232.

**Comment by vbarrielle** [comment]
But this particular issue could be solved for 0.10.

**Comment by mulimoen** [comment]
It is a big stopper here too, the new constructors would not require elements being `Clone` nor `Copy`

**Comment by vbarrielle** [comment]
I see, what would the behavior of the non-sorting `new` constructor be? Error returning, same as the other structure checks?

**Comment by mulimoen** [comment]
I think error returning is the cleanest, we would need this constructor anyway. We can always rename and add a panicking one if we find this cumbersome.

**Comment by vbarrielle** [comment]
Ok, let's include the `new` and `new_sorted` constructors for 0.10 then. As you say, a panicking constructor can always be added later. I'm goind to add a separate issue as in my mind this one was more about removing the `Copy` bound that's present on most linear algebra functions.

**Comment by vbarrielle** [comment]
Fixed by #276.
