### ISSUE TITLE
Generalize ndarray version support

### ISSUE THREAD

**Issue by pmarks** [vbarrielle/sprs#142]
I've manually run `cargo test` with all ndarray versions that fall in the range:
`ndarray = ">=0.11, <0.13.0"` -- they all compile and pass test.  Could we generalize the ndarray version support to cover this?

A few people I work with have updated ndarray and gotten 'trait not implemented' errors because the top-level ndarray version doesn't match the sprs version.

(edited based on @rth's suggestion -- we should allow all of `0.12.*`)

**Comment by rth** [comment]
> Could we generalize the ndarray version support to cover this?

+1 -- I had the same issue recently.

**Comment by rth** [comment]
Maybe, `ndarray = ">=0.11, <0.13.0"` assuming ndarray doesn't break semver for 0.12?
