### ISSUE TITLE
LdlNumeric::update() should return a Result

### ISSUE THREAD

**Issue by michael-p** [vbarrielle/sprs#149]
Since the decomposition can fail `LdlNumeric::update()` and `LdlLongNumeric::update()` in the `sprs_suitesparse_ldl` crate should return a `Result` type to indicate failure.

SuiteSparse actually does returns a failure code in `ldl_numeric()` and `ldl_l_numeric()` (see e.g. https://github.com/jluttine/suitesparse/blob/master/LDL/Source/ldl.c#L253). Note that this return type `LDL_int` there is currently not correct in the `suitesparse_ldl_sys` bindings crate (specified as returning `()` there).

**Comment by vbarrielle** [comment]
Good point, thanks for the report.
