### ISSUE TITLE
to_csr() can create matrices with invalid indptr

### ISSUE THREAD

**Issue by avangogo** [vbarrielle/sprs#170]
It seems that the conversion function from TrimatI to CsMat does not work properly when the matrix has empty lines. The following code

```rust
let tri_mat = sprs::TriMatI::new((2,4));
let m: sprs::CsMat<u64> = tri_mat.to_csr();
println!("{:?}", m);
let _ = m.get(1,1); 
```

outputs 

```CsMatBase { storage: CSR, nrows: 2, ncols: 4, indptr: [0, 1], indices: [0], data: [0] }```

and then logically panics with `index out of bounds: the len is 2 but the index is 2` in ...`/sprs-0.6.5/src/sparse/csmat.rs:1056:20`.

**Comment by vbarrielle** [comment]
Thanks for the report, I should have a fix soon.
