### ISSUE TITLE
Documentation is broken

### ISSUE THREAD

**Issue by technic** [vbarrielle/sprs#181]
Hi,
thanks for the librariy
https://docs.rs/crate/sprs/0.7.0 is broken
I have to use 0.6.5 docs as fallback
Could you check it please?

**Comment by vbarrielle** [comment]
Thanks for the report, I've pushed a version 0.7.1 that should fix the docs building issue on docs.rs, looks like it's taking some time for docs.rs to pick up a new crate and build it.

**Comment by vbarrielle** [comment]
Correctly built: https://docs.rs/sprs/0.7.1/sprs/
