### ISSUE TITLE
One-Hot Matrix constructor

### ISSUE THREAD

**Issue by austinjones** [vbarrielle/sprs#190]
Would you be interested in a one-hot matrix constructor?  I'm working on one based on sprs.

If constructed from a sparse matrix, the constructor would reduce each inner vector to the element with the maximum value.  As a result, along the inner dimension, exactly one element would be non-zero (with value of 1).

If you are interested, let me know and I'll polish it up for a PR.

**Comment by vbarrielle** [comment]
Hello,

That looks nice to have, please go ahead.

Thanks!
