### ISSUE TITLE
Make rayon optional

### ISSUE THREAD

**Issue by mulimoen** [vbarrielle/sprs#208]
After upgrading to `0.8` the crate can no longer be used on the `wasm32` target, as a threadpool can not be initialized:

> panicked at 'The global thread pool has not been initialized.: ThreadPoolBuildError { kind: IOError(Custom { kind: Other, error: "operation not supported on this platform" }) }'

Could the dependency on rayon be made into a (default) feature instead, to allow usage on this platform?

**Comment by vbarrielle** [comment]
Yes having it default but optional seems the way to go.
