### ISSUE TITLE
0.9 breakage wishlist

### ISSUE THREAD

**Issue by vbarrielle** [vbarrielle/sprs#224]
There are already two breaking changes pending for [the 0.9 version](https://github.com/vbarrielle/sprs/milestone/2). This issue is a call for ideas of needed breaking changes, in order to be able to group most of them for version 0.9. This way I hope to reduce the version churn.

**Comment by vbarrielle** [comment]
Wondering if it's time we get 0.9 out. @mulimoen do you have an opinion on this? Maybe you have more changes you'd like to push before?

**Comment by mulimoen** [comment]
@vbarrielle I can't think of any obvious breakages, and I don't have any changes currently pending

**Comment by vbarrielle** [comment]
Ok, I'll probably publish 0.9 this weekend then.

**Comment by vbarrielle** [comment]
0.9 is [published](https://crates.io/crates/sprs/0.9.0) :tada:
