### ISSUE TITLE
Publish new version of sprs to crates

### ISSUE THREAD

**Issue by bytesnake** [vbarrielle/sprs#291]
We need the `ndarray = 0.15` dependency upstream for linfa (see https://github.com/rust-ml/linfa/issues/124). Would it be possible to push a new version to crates?

**Comment by mulimoen** [comment]
I can see if I can push a new update after work today (6 hours or so). Are you only using `sprs`, or also crates using `sprs`? @vbarrielle, I dont have publish rights to crates other than `sprs`, could you send me an invitation to the other crates in this repo?

**Comment by mulimoen** [comment]
@bytesnake You can find 0.11.0 on crates.io now!
