### ISSUE TITLE
How to directly provide indptr/indices/data to CsMatI (without sorting, etc)

### ISSUE THREAD

**Issue by chetmurthy** [vbarrielle/sprs#300]
First, wow, this is a really nice package, and I'm hacking furiously with it.  Lovely stuff.

I'm building quite large sparse matrices (4-64m entries in (4m x 4m) matrices), and building thousands of them, that I'll add up and then do other things with.  I might need to export them to Python or C++, so the `into_raw_storage` will be perfect.

To construct the individual matrices, I have code that uses `TriMat::from_triplets`, but I see that that is then processed to produce the IndPtr representation that is used internally.  The code that builds the three vectors I hand to `from_triplets`, though, was taken from Python, and was originally used to produce the same three vectors for wrappering by scipy's `csr_matrix`.  So (IIUC)) they have the right format that I could just slam them into a `CSMatrixI` and run with them.

Looking at `TriMatIter::into_cs`, it appears that the code there sorts by (for CSR) (row, column).  The generation code I use already produces the `indptr` vector in row-sorted order (as it turns out, there's only one nonzero entry per row, so it's pretty trivial).

I've benchmarked with Criterion, and the difference in CPU time for a 4mx4m matrix is ..... 191ms down to 50ms.  So about a factor of 4, and multiplied by 40k to 160k matrices, that adds up to a massive amount of time.

It would seem like it's safe to merely *check* that the row, col are sorted, and in that case, one could just slam the vectors into the `CsMatI`.

Does this make sense?  Is there some entrypoint that already does this sort of thing, that I didn't find ?  If this makes sense, I will try to write a PR that does this.

I'm pretty new to Rust, and new to this storage format, but .... I think if I can figure out the algorithmic details, the language shouldn't be an issue.

Your advice appreciated.

**Comment by mulimoen** [comment]
Glad you like the library. Is https://docs.rs/sprs/0.11.0/sprs/struct.CsMatBase.html#method.new or the unsafe assumed sorted constructor of https://docs.rs/sprs/0.11.0/sprs/struct.CsMatBase.html#method.new_unchecked usable for you?

**Comment by chetmurthy** [comment]
Lovely!  It worked!  I just didn't see the function in my searching.  Thank you so much for pointing it out.  And again, for writing this thing.

Maybe sometime soon, I'll be able to write an eigenvalue solver for this format.

Closing!
