### ISSUE TITLE
Storage should be implemented as an unsafe trait

### ISSUE THREAD

**Issue by vbarrielle** [vbarrielle/sprs#39]
See rust-lang/rust#29701
The implementation in bluss/rust-ndarray looks like a good example of how to do it.

**Comment by bluss** [comment]
Maybe it doesn't matter if all constructors are locked down?

**Comment by vbarrielle** [comment]
Maybe indeed. Having a dedicated trait can be beneficial in some cases though.
For instance, a sparse vector can be seen as a sparse matrix, but currently 
this is done by creating a sparse matrix with Vec as a backend for the indptr 
storage. Having a trait would enable having a [usize; 2] for the indptr.

**Comment by vbarrielle** [comment]
Since the only valid reason was the matrix view around a vector, #111 fixes this issue.
