### ISSUE TITLE
Hosted documentation needs to be updated

### ISSUE THREAD

**Issue by dylanede** [vbarrielle/sprs#44]
I've noticed that there are features available in the crates.io published version that are not shown in the online documentation, such as `LdlNumeric` and `LdlSymbolic`, so really a `cargo doc` should be redone.

**Comment by vbarrielle** [comment]
I've just updated the docs, should be ok now.

**Comment by dylanede** [comment]
There seems to be some files missing. For example try clicking on LdlNumeric in https://vbarrielle.github.io/sprs/doc/sprs/sparse/linalg/cholesky/

**Comment by vbarrielle** [comment]
Should be fixed now. I'll leave this issue open for a while, feel free to report any other issue.
Thanks for the coverage, it's really nice 'cause I don't spend enough time checking the state of my docs...

**Comment by vbarrielle** [comment]
Closing as the doc is now up-to-date with latest changes.

**Comment by dylanede** [comment]
You might want to consider getting Travis to automatically update the docs on every update to master. There's a tutorial at http://hoverbear.org/2015/03/07/rust-travis-github-pages/

**Comment by vbarrielle** [comment]
Thanks for the tip, I'l look into that.
